"""initial schema

Revision ID: 6fb90280d94d
Revises: 
Create Date: 2026-09-11 14:09:24.199875

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '6fb90280d94d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_insights',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.BigInteger(), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('rising', 'stable', 'declining', name='trenddirection', native_enum=False, length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('highlights', sa.JSON(), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('high_impact_count', sa.Integer(), nullable=False),
    sa.Column('coverage_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trend_insights', schema=None) as batch_op:
        batch_op.create_index('idx_trend_competitor_created', ['competitor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trend_insights_competitor_id'), ['competitor_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('weekly_reports',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('report_type', sa.Enum('weekly', 'monthly', name='reporttype', native_enum=False, length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('range_start', sa.Date(), nullable=False),
    sa.Column('range_end', sa.Date(), nullable=False),
    sa.Column('competitor_count', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_reports', schema=None) as batch_op:
        batch_op.create_index('idx_report_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_reports_user_id'), ['user_id'], unique=False)

    op.create_table('competitors',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('official_url', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', name='competitorstatus', native_enum=False, length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitors_user_id'), ['user_id'], unique=False)

    op.create_table('monitor_sources',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.Enum('homepage', 'pricing', 'changelog', 'blog', 'docs', 'status', 'rss', 'app_store', name='sourcetype', native_enum=False, length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('render_mode', sa.Enum('browser', 'http', name='rendermode', native_enum=False, length=10), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=10), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitor_sources', schema=None) as batch_op:
        batch_op.create_index('idx_source_competitor_enabled', ['competitor_id', 'enabled'], unique=False)

    op.create_table('page_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.Enum('homepage', 'pricing', 'changelog', 'blog', 'docs', 'status', 'rss', 'app_store', name='sourcetype', native_enum=False, length=30), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('raw_html_path', sa.String(length=255), nullable=True),
    sa.Column('clean_text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('fail_reason', sa.Text(), nullable=True),
    sa.Column('change_detected', sa.Boolean(), nullable=False),
    sa.Column('diff_text', sa.Text(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['monitor_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_snapshot_competitor_crawled', ['competitor_id', 'crawled_at'], unique=False)
        batch_op.create_index('idx_snapshot_source_crawled', ['source_id', 'crawled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_snapshots_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_snapshots_content_hash'), ['content_hash'], unique=False)

    op.create_table('intelligence_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('competitor_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.Enum('new_feature', 'price_change', 'content_update', 'public_sentiment', 'other', name='eventtype', native_enum=False, length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('diff_detail', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['page_snapshots.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['monitor_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intelligence_events', schema=None) as batch_op:
        batch_op.create_index('idx_event_competitor_created', ['competitor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_events_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_events_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intelligence_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intelligence_events_source_id'))
        batch_op.drop_index(batch_op.f('ix_intelligence_events_competitor_id'))
        batch_op.drop_index('idx_event_competitor_created')

    op.drop_table('intelligence_events')
    with op.batch_alter_table('page_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_snapshots_content_hash'))
        batch_op.drop_index(batch_op.f('ix_page_snapshots_competitor_id'))
        batch_op.drop_index('idx_snapshot_source_crawled')
        batch_op.drop_index('idx_snapshot_competitor_crawled')

    op.drop_table('page_snapshots')
    with op.batch_alter_table('monitor_sources', schema=None) as batch_op:
        batch_op.drop_index('idx_source_competitor_enabled')

    op.drop_table('monitor_sources')
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitors_user_id'))

    op.drop_table('competitors')
    with op.batch_alter_table('weekly_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_reports_user_id'))
        batch_op.drop_index('idx_report_user_created')

    op.drop_table('weekly_reports')
    op.drop_table('users')
    with op.batch_alter_table('trend_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trend_insights_competitor_id'))
        batch_op.drop_index('idx_trend_competitor_created')

    op.drop_table('trend_insights')
    # ### end Alembic commands ###
